// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using linkquery.Data;

#nullable disable

namespace linkquery.Migrations
{
    [DbContext(typeof(WebDbContext))]
    [Migration("20231224075959_initial Create")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("linkquery.Data.Class", b =>
                {
                    b.Property<int>("C_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("C_id"));

                    b.Property<string>("C_name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("Facultyf_id")
                        .HasColumnType("int");

                    b.Property<int?>("Romm_num")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("f_id")
                        .HasColumnType("int");

                    b.HasKey("C_id");

                    b.HasIndex("Facultyf_id");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("linkquery.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("linkquery.Data.Enrolled", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("C_id")
                        .HasColumnType("int");

                    b.Property<int?>("ClassC_id")
                        .HasColumnType("int");

                    b.Property<int>("S_id")
                        .HasColumnType("int");

                    b.Property<int?>("StudentS_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClassC_id");

                    b.HasIndex("StudentS_id");

                    b.ToTable("Enrolled");
                });

            modelBuilder.Entity("linkquery.Data.Faculty", b =>
                {
                    b.Property<int>("f_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("f_id"));

                    b.Property<int>("dept_id")
                        .HasMaxLength(25)
                        .HasColumnType("int");

                    b.Property<int>("f_standing")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("f_id");

                    b.ToTable("Faculty");
                });

            modelBuilder.Entity("linkquery.Data.Student", b =>
                {
                    b.Property<int>("S_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("S_id"));

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("S_name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Standing")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.HasKey("S_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("linkquery.Data.Class", b =>
                {
                    b.HasOne("linkquery.Data.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("Facultyf_id");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("linkquery.Data.Enrolled", b =>
                {
                    b.HasOne("linkquery.Data.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassC_id");

                    b.HasOne("linkquery.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentS_id");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
